# try to achieve the celler automata with python
### use print() to get the graphic of each generation
### advise: [using python to make celler automata](http://blog.csdn.net/parameter_/article/details/70301221)

下面介绍生命游戏的构成及规则: 

1. 元胞分布在规则划分的网格上； 
2. 元胞具有0，1两种状态，0代表”死”，l代表”生”； 
3. 元胞以相邻的8个元胞为邻居。即Moore邻居形式； 
4. 一个元胞的生死由其在该时刻本身的生死状态和周围八个邻居的状态 (确切讲是状态的和)决定: 
> * 在当前时刻，如果一个元胞状态为”生”，且八个相邻元胞中有两个或三个的状态为”生”，则在下–时刻该元胞继续保持为”生”，否则”死”去； 
  * 在当前时刻。如果一个元胞状态为”死”。且八个相邻元胞中正好有三个为”生”。则该元胞在下一时刻 “复活”。否则保持为”死”。 

In [1]:
import numpy as np

In [6]:
class lifegame(object):
    def __init__(self):
        self.lifepoint=np.random.randint(2,size=(18,18)).astype(np.uint8)
        self.cols,self.rows=self.lifepoint.shape
    def __iter__(self):
        return self
    def next(self):
        newcopy=self.lifepoint.copy()
        for i in range(1,self.cols):
            for j in range(1,self.rows):
                lifestate=self.lifepoint[i,j]
                area=self.lifepoint[i-1:i+2,j-1:j+2]
                d=np.sum(area)-lifestate
                
                # at this generation, if the center cell and 2 or 3 neighbors are alive, it maintains active.
                if lifestate: # if lifestate (== 1 == True):
                    if d==3 or d==2:
                        self.lifepoint[i,j]=1
                    else:
                        self.lifepoint[i,j]=0
                else:
                # if the center cell is dead, but 3 neighbors are live, it will rebirth.
                    if d==3:
                        self.lifepoint[i,j]=1
        
        # the situation at each edge of the array is different and complecate.
        
        for j in range(1,self.rows):
            edgelifestate1=newcopy[0,j]
            area1=newcopy[0:2,j-1:j+2]
            d1=np.sum(area1)-edgelifestate1
            if edgelifestate1:
                if d1==3 or d1==2:
                    self.lifepoint[0,j]=1
                else:
                    self.lifepoint[0,j]=0
            else:
                if d1==3:
                    self.lifepoint[0,j]=1

        for j in range(1, self.rows):
            edgelifestate2 = newcopy[self.cols-1, j]
            area2 = newcopy[self.cols-2:self.cols, j - 1:j + 2]
            d2 = np.sum(area2) - edgelifestate2
            if edgelifestate2:
                if d2 == 3 or d2 == 2:
                    self.lifepoint[self.cols-1, j] = 1
                else:
                    self.lifepoint[self.cols-1, j] = 0
            else:
                if d2 == 3:
                    self.lifepoint[self.cols-1, j] = 1
        for i in range(1, self.cols):
            edgelifestate3 = newcopy[i, 0]
            area3 = newcopy[i-1:i+2, 0:2]
            d3 = np.sum(area3) - edgelifestate2
            if edgelifestate3:
                if d3 == 3 or d3 == 2:
                    self.lifepoint[i, 0] = 1
                else:
                    self.lifepoint[i, 0] = 0
            else:
                if d3 == 3:
                    self.lifepoint[i, 0] = 1
        for i in range(1, self.cols):
            edgelifestate4 = newcopy[i,self.rows-1]
            area4 = newcopy[i :i+2, self.rows-2:self.rows]
            d4 = np.sum(area4) - edgelifestate4
            if edgelifestate3:
                if d4 == 3 or d4 == 2:
                    self.lifepoint[i, 0] = 1
                else:
                    self.lifepoint[i, 0] = 0
            else:
                if d4 == 3:
                    self.lifepoint[i, 0] = 1
        coner1=newcopy[0,0]
        areacorner1=newcopy[0:2,0:2]
        c1=np.sum(areacorner1)
        if coner1:
            if c1==3 or c1==2:
                self.lifepoint[0,0]=1
            else:
                self.lifepoint[0,0]=0
        else:
            if c1==3:
                self.lifepoint[0,0]=1
        corner2=newcopy[0,self.cols-1]
        areacorner2=newcopy[0:2,self.cols-2:self.cols]
        c2=np.sum(areacorner2)
        if corner2:
            if c2==3 or c2==2:
                self.lifepoint[0,self.cols-1]=1
            else:
                self.lifepoint[0,self.cols-1]=0
        else:
            if c2==3:
                self.lifepoint[0,self.cols-1]=1
        corner3=newcopy[self.cols-1,0]
        areacorner3=newcopy[self.cols-2:self.cols,0:2]
        c3=np.sum(areacorner3)
        if corner3:
            if c3==3 or c3==2:
                self.lifepoint[self.cols-1,0]=1
            else:
                self.lifepoint[self.cols-1,0]=0
        else:
            if c3==3:
                self.lifepoint[self.cols-1, 0]=1
        corner4 = newcopy[self.cols - 1, self.cols-1]
        areacorner4 = newcopy[self.cols - 2:self.cols, self.rows-2:self.rows]
        c4 = np.sum(areacorner4)
        if corner4:
            if c4 == 3 or c4 == 2:
                self.lifepoint[self.cols - 1, self.rows-1] = 1
            else:
                self.lifepoint[self.cols - 1, self.rows-1] = 0
        else:
            if c3 == 3:
                self.lifepoint[self.cols - 1, self.rows-1] = 1
        return self.lifepoint


In [7]:
# test this class
a=lifegame()
for i in range(10):
    print(a.next())
    print('============================================')

[[0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 1 1]
 [0 1 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 1]
 [0 0 0 1 1 0 1 1 1 0 0 0 0 0 1 1 0 1]
 [1 0 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 0]
 [1 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0]
 [1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0]
 [1 1 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1]
 [0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 1 0 0 1 0 0 0 0 1]
 [1 1 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0]
 [1 0 0 1 0 1 0 1 1 0 0 0 0 1 1 0 0 1]
 [1 1 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0 1]
 [1 1 0 1 0 1 0 0 0 1 1 1 0 1 1 0 1 1]]
[[0 1 0 1 1 1 1 1 0 0 0 1 1 1 0 0 1 1]
 [0 1 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 1]
 [0 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1]
 [1 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0]
 [0 1 0 0 0 0 1 0 1 1 1 0 1 0 0 1 1 0]
 [0 0 0 0 0 1 1 0 0 0 1 

/Users/dengdingshan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: RuntimeWarning: overflow encountered in ulong_scalars
